import apiClient from '../apiClient.js';

// Thin wrapper over the standalone Zephyr API (/api/v1/zephyr). Every call
// returns the unwrapped `data` payload.
const unwrap = (res) => res.data.data;

export const zephyrApi = {
  me: () => apiClient.get('/zephyr/me').then(unwrap),
  settings: () => apiClient.get('/zephyr/settings').then(unwrap),
  updateSettings: (body) => apiClient.patch('/zephyr/settings', body).then(unwrap),
  categories: (kind) => apiClient.get('/zephyr/categories', { params: kind ? { kind } : {} }).then(unwrap),
  createCategory: (body) => apiClient.post('/zephyr/categories', body).then(unwrap),
  updateCategory: (id, body) => apiClient.patch(`/zephyr/categories/${id}`, body).then(unwrap),
  deleteCategory: (id) => apiClient.delete(`/zephyr/categories/${id}`).then(unwrap),
  people: (params) => apiClient.get('/zephyr/people', { params }).then(unwrap),
  person: (id) => apiClient.get(`/zephyr/people/${id}`).then(unwrap),
  addAssignment: (id, body) => apiClient.post(`/zephyr/people/${id}/assignments`, body).then(unwrap),
  updateAssignment: (id, aid, body) => apiClient.patch(`/zephyr/people/${id}/assignments/${aid}`, body).then(unwrap),
  deleteAssignment: (id, aid) => apiClient.delete(`/zephyr/people/${id}/assignments/${aid}`).then(unwrap),
  salaries: (month) => apiClient.get('/zephyr/salaries', { params: { month } }).then(unwrap),
  generateSalaries: (month) => apiClient.post('/zephyr/salaries/generate', { month }).then(unwrap),
  updateSalary: (id, body) => apiClient.patch(`/zephyr/salaries/${id}`, body).then(unwrap),
  approveSalary: (id) => apiClient.post(`/zephyr/salaries/${id}/approve`).then(unwrap),
  unapproveSalary: (id, reason) => apiClient.post(`/zephyr/salaries/${id}/unapprove`, { reason }).then(unwrap),
  paySalary: (id, paid_on) => apiClient.post(`/zephyr/salaries/${id}/pay`, paid_on ? { paid_on } : {}).then(unwrap),
  deleteSalary: (id) => apiClient.delete(`/zephyr/salaries/${id}`).then(unwrap),
  myWork: () => apiClient.get('/zephyr/my-work').then(unwrap),
  createPerson: (body) => apiClient.post('/zephyr/people', body).then(unwrap),
  updatePerson: (id, body) => apiClient.patch(`/zephyr/people/${id}`, body).then(unwrap),
  deletePerson: (id) => apiClient.delete(`/zephyr/people/${id}`).then(unwrap),
  parties: (params) => apiClient.get('/zephyr/parties', { params }).then((res) => res.data),
  party: (id) => apiClient.get(`/zephyr/parties/${id}`).then(unwrap),
  createParty: (body) => apiClient.post('/zephyr/parties', body).then(unwrap),
  updateParty: (id, body) => apiClient.patch(`/zephyr/parties/${id}`, body).then(unwrap),
  deleteParty: (id) => apiClient.delete(`/zephyr/parties/${id}`).then(unwrap),
  importParties: (rows) => apiClient.post('/zephyr/parties/import', { rows }).then(unwrap),
  leads: (params) => apiClient.get('/zephyr/leads', { params }).then(unwrap),
  leadSummary: () => apiClient.get('/zephyr/leads/summary').then(unwrap),
  leadFollowUps: () => apiClient.get('/zephyr/leads/follow-ups').then(unwrap),
  leadOwners: () => apiClient.get('/zephyr/leads/owners').then(unwrap),
  lead: (id) => apiClient.get(`/zephyr/leads/${id}`).then(unwrap),
  createLead: (body) => apiClient.post('/zephyr/leads', body).then(unwrap),
  updateLead: (id, body) => apiClient.patch(`/zephyr/leads/${id}`, body).then(unwrap),
  deleteLead: (id) => apiClient.delete(`/zephyr/leads/${id}`).then(unwrap),
  moveLead: (id, body) => apiClient.post(`/zephyr/leads/${id}/stage`, body).then(unwrap),
  reopenLead: (id, body) => apiClient.post(`/zephyr/leads/${id}/reopen`, body).then(unwrap),
  leadActivities: (id) => apiClient.get(`/zephyr/leads/${id}/activities`).then(unwrap),
  addLeadActivity: (id, body) => apiClient.post(`/zephyr/leads/${id}/activities`, body).then(unwrap),
  setFollowUpDone: (id, activityId, done) => apiClient.patch(`/zephyr/leads/${id}/activities/${activityId}`, { follow_up_done: done }).then(unwrap),
  projects: (params) => apiClient.get('/zephyr/projects', { params }).then(unwrap),
  projectSummary: () => apiClient.get('/zephyr/projects/summary').then(unwrap),
  project: (id) => apiClient.get(`/zephyr/projects/${id}`).then(unwrap),
  createProject: (body) => apiClient.post('/zephyr/projects', body).then(unwrap),
  projectFromLead: (leadId, body) => apiClient.post(`/zephyr/projects/from-lead/${leadId}`, body || {}).then(unwrap),
  updateProject: (id, body) => apiClient.patch(`/zephyr/projects/${id}`, body).then(unwrap),
  deleteProject: (id) => apiClient.delete(`/zephyr/projects/${id}`).then(unwrap),
  addMilestone: (id, body) => apiClient.post(`/zephyr/projects/${id}/milestones`, body).then(unwrap),
  updateMilestone: (id, mid, body) => apiClient.patch(`/zephyr/projects/${id}/milestones/${mid}`, body).then(unwrap),
  deleteMilestone: (id, mid) => apiClient.delete(`/zephyr/projects/${id}/milestones/${mid}`).then(unwrap),
  addWorkOrder: (id, body) => apiClient.post(`/zephyr/projects/${id}/work-orders`, body).then(unwrap),
  updateWorkOrder: (id, wid, body) => apiClient.patch(`/zephyr/projects/${id}/work-orders/${wid}`, body).then(unwrap),
  deleteWorkOrder: (id, wid) => apiClient.delete(`/zephyr/projects/${id}/work-orders/${wid}`).then(unwrap),
  ledger: (params) => apiClient.get('/zephyr/ledger', { params }).then((res) => res.data),
  ledgerEntry: (id) => apiClient.get(`/zephyr/ledger/${id}`).then(unwrap),
  createEntry: (body) => apiClient.post('/zephyr/ledger', body).then(unwrap),
  updateEntry: (id, body) => apiClient.patch(`/zephyr/ledger/${id}`, body).then(unwrap),
  deleteEntry: (id) => apiClient.delete(`/zephyr/ledger/${id}`).then(unwrap),
  importEntries: (rows) => apiClient.post('/zephyr/ledger/import', { rows }).then(unwrap),
  projectMoney: (id) => apiClient.get(`/zephyr/projects/${id}/money`).then(unwrap),
  partyStatement: (id) => apiClient.get(`/zephyr/parties/${id}/statement`).then(unwrap),
  overview: (params) => apiClient.get('/zephyr/overview', { params }).then(unwrap),
  overviewSalaries: (params) => apiClient.get('/zephyr/overview/salaries', { params }).then(unwrap),
  plans: (params) => apiClient.get('/zephyr/financials/plans', { params }).then(unwrap),
  savePlan: (body) => apiClient.put('/zephyr/financials/plans', body).then(unwrap),
  deletePlan: (id) => apiClient.delete(`/zephyr/financials/plans/${id}`).then(unwrap),
  planVsActual: (params) => apiClient.get('/zephyr/financials/plan-vs-actual', { params }).then(unwrap),
  projection: () => apiClient.get('/zephyr/financials/projection').then(unwrap),
  closes: (params) => apiClient.get('/zephyr/financials/closes', { params }).then(unwrap),
  closeMonth: (month) => apiClient.post('/zephyr/financials/close', { month }).then(unwrap),
  reopenMonth: (month, reason) => apiClient.post('/zephyr/financials/reopen', { month, reason }).then(unwrap),
  statement: (params) => apiClient.get('/zephyr/financials/statement', { params }).then(unwrap),
  statementFile: (params) => apiClient.get('/zephyr/financials/statement', { params, responseType: 'blob' }).then((res) => res.data),
  documents: (owner_type, owner_id) => apiClient.get('/zephyr/documents', { params: { owner_type, owner_id } }).then(unwrap),
  uploadDocument: (form) => apiClient.post('/zephyr/documents', form).then(unwrap),
  updateDocument: (id, body) => apiClient.patch(`/zephyr/documents/${id}`, body).then(unwrap),
  deleteDocument: (id) => apiClient.delete(`/zephyr/documents/${id}`).then(unwrap),
  audit: (params) => apiClient.get('/zephyr/audit', { params }).then(unwrap),
};

export function zephyrError(error, fallback = 'Something went wrong') {
  const data = error?.response?.data;
  return data?.errors?.[0]?.message || data?.message || fallback;
}
